-- 1. Таблица Меню (menu)
CREATE TABLE IF NOT EXISTS menu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    price INTEGER NOT NULL,
    category TEXT NOT NULL,
    is_available BOOLEAN NOT NULL DEFAULT TRUE
);

-- 2. Таблица Диалогов (conversations)
CREATE TABLE IF NOT EXISTS conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone TEXT UNIQUE NOT NULL,
    messages JSONB NOT NULL DEFAULT '[]'::jsonb,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Функция для автоматического обновления времени изменения диалога
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Триггер для обновления updated_at при изменении диалога
CREATE OR REPLACE TRIGGER update_conversations_updated_at
BEFORE UPDATE ON conversations
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- 3. Таблица Заказов (orders)
-- Начинаем нумерацию заказов с 1000 для красивого вида на чеках
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    phone TEXT NOT NULL,
    name TEXT NOT NULL,
    address TEXT NOT NULL,
    items JSONB NOT NULL, -- Массив объектов [{id, name, quantity, price}]
    total INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'new', -- 'new', 'ready', 'completed'
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- 4. Наполнение меню тестовыми позициями (добавление роллов, суши, напитков)
INSERT INTO menu (name, description, price, category, is_available) VALUES
('Филадельфия Классик', 'Классический ролл с лососем, сливочным сыром крем-чиз и огурцом', 2490, 'Роллы', TRUE),
('Калифорния с крабом', 'Ролл с крабовым миксом, огурцом, майонезом и икрой тобико', 1990, 'Роллы', TRUE),
('Дракон Ролл', 'Ролл с копченым угрем, сливочным сыром, соусом унаги и кунжутом', 2890, 'Роллы', TRUE),
('Сяке Маки', 'Простой ролл со свежим лососем', 1290, 'Суши', TRUE),
('Каппа Маки', 'Вегетарианский ролл со свежим огурцом и кунжутом', 990, 'Суши', TRUE),
('Coca-Cola 0.5', 'Прохладительный газированный напиток в пластиковой бутылке', 450, 'Напитки', TRUE),
('Вода ASU 0.5 без газа', 'Природная минеральная вода', 300, 'Напитки', TRUE),
('Соевый соус (доп)', 'Дополнительная порция соевого соуса, 50мл', 150, 'Соусы', TRUE),
('Васаби порция', 'Дополнительная порция острого васаби, 15гр', 100, 'Соусы', TRUE),
('Имбирь порция', 'Дополнительная порция маринованного имбиря, 30гр', 100, 'Соусы', TRUE)
ON CONFLICT DO NOTHING;

-- 5. Включение Supabase Realtime для таблицы заказов (orders)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 
        FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'orders'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE orders;
    END IF;
END $$;

-- 6. Отключение Row Level Security (RLS) для тестирования и разработки
ALTER TABLE menu DISABLE ROW LEVEL SECURITY;
ALTER TABLE conversations DISABLE ROW LEVEL SECURITY;
ALTER TABLE orders DISABLE ROW LEVEL SECURITY;
